### ISSUE TITLE
Errors appear when making

### ISSUE THREAD

**Issue by rjiang2021** [SoftSimu/SymPhas#1]
Hi,

I am trying to install the Symphas but a make error occurs.
My system is Fedora28 with gcc version 8.3.1.
The error is following:
...
[ 52%] Built target symphas_io
[ 54%] Building CXX object sol/CMakeFiles/symphas_sol_o.dir/src/boundarysystem.cpp.o
In file included from /home/rjiang/Downloads/software/SymPhas/sol/inc/boundarysystem.h:29,
                 from /home/rjiang/Downloads/software/SymPhas/sol/src/boundarysystem.cpp:22:
/home/rjiang/Downloads/software/SymPhas/sol/inc/boundarygroup.h: In function ‘bool symphas::internal::all_periodic(BoundaryType (&)[D])’:
/home/rjiang/Downloads/software/SymPhas/sol/inc/boundarygroup.h:100:15: error: ‘transform_reduce’ is not a member of ‘std’
   return std::transform_reduce(
               ^~~~~~~~~~~~~~~~
/home/rjiang/Downloads/software/SymPhas/sol/inc/boundarygroup.h:100:15: note: suggested alternative: ‘random_device’
   return std::transform_reduce(
               ^~~~~~~~~~~~~~~~
               random_device
make[2]: *** [sol/CMakeFiles/symphas_sol_o.dir/build.make:63: sol/CMakeFiles/symphas_sol_o.dir/src/boundarysystem.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:513: sol/CMakeFiles/symphas_sol_o.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I appreciate your help!
Thank you!

**Comment by MetricManifold** [comment]
Could you share the cmake command you used to configure the build?

**Comment by rjiang2021** [comment]
Thank you for your reply.

I have tried other gcc versions(10.2.1 and 9.3.1).
These two versions seem to work well.
But there are still some complication problems.
My installation steps are as follows.
1.  cmake -DCMAKE_INSTALL_PREFIX=/usr/local/symphas ..
2. make
A make error occurs as following:
Scanning dependencies of target symphas_all
[ 88%] Building CXX object CMakeFiles/symphas_all.dir/prereq.cpp.o
In file included from /home/rjiang/Downloads/software/Symphas/prereq.cpp:21:
/home/rjiang/Downloads/software/Symphas/prereq.h:40:1: error: qualified name does not name a class before ‘{’ token
   40 | {
      | ^
/home/rjiang/Downloads/software/Symphas/prereq.h:49:1: error: qualified name does not name a class before ‘{’ token
   49 | {
      | ^
/home/rjiang/Downloads/software/Symphas/prereq.h:81:1: error: qualified name does not name a class before ‘{’ token
   81 | {
      | ^
/home/rjiang/Downloads/software/Symphas/prereq.h:88:1: error: qualified name does not name a class before ‘{’ token
   88 | {
      | ^
/home/rjiang/Downloads/software/Symphas/prereq.h:95:1: error: qualified name does not name a class before ‘{’ token
   95 | {
      | ^
make[2]: *** [CMakeFiles/symphas_all.dir/build.make:63: CMakeFiles/symphas_all.dir/prereq.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/symphas_all.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

In order to solve this problem, I modified the header filer “/Symphas/prereq.h”, in which I add 
“#include "/home/rjiang/Downloads/software/Symphas/sol/inc/solve.h"” to include the file “solve.h”. Then, I execute the make command again and it passed successfully.

I don’t know if there is any other way to solve this problem.

3. sudo make install

After successful installation, I tried this example in “example/simple-driver” by executing the following commands:
1. cd example/simple-driver/build
2. cmake -DCMAKE_BUILD_TYPE:STRING:="Release" -DUSE_IO:BOOL="True" -DSOLVER_INCLUDE_HEADER_DIR:PATH="/usr/local/symphas/include" -DSOLVER_INCLUDE_HEADER_NAME:FILEPATH="solverinclude.h" -DMODEL_INCLUDE_HEADER_DIR:PATH="/usr/local/symphas/include" -DMODEL_INCLUDE_HEADER_NAME:FILEPATH="modelinclude.h" ..
3. make
Then, an executable “symphas_impl” is created!

BUT, when i tried the second option by using “g++” to compile the executable file, it failed.
My commands are following:
g++ -o a.out main.cpp -std=c++17 -I/usr/local/symphas/include -L/usr/local/symphas/lib -lsymphas_all -ltbb

The screens displays the error message as follows.
main.cpp: In function ‘int main(int, char**)’:
main.cpp:41:16: error: ‘SolverSP’ was not declared in this scope; did you mean ‘Solver’?
   41 |  model_EX_t<2, SolverSP<Stencil2d2h<5, 9, 6>>> model{ pp };
      |                ^~~~~~~~
      |                Solver
main.cpp:41:44: error: template argument 2 is invalid
   41 |  model_EX_t<2, SolverSP<Stencil2d2h<5, 9, 6>>> model{ pp };
      |                                            ^~
main.cpp:41:46: error: expected unqualified-id before ‘>’ token
   41 |  model_EX_t<2, SolverSP<Stencil2d2h<5, 9, 6>>> model{ pp };
      |                                              ^
main.cpp:42:25: error: ‘model’ was not declared in this scope; did you mean ‘Model’?
   42 |  symphas::find_solution(model, dt, 50);
      |                         ^~~~~
      |                         Model
main.cpp:43:30: error: expected primary-expression before ‘)’ token
   43 |  auto pfdata = model.grid<0>();
      |                              ^

I don’t know how to solve this complication problem.

**Comment by MetricManifold** [comment]
I will update the tutorial with a more description, since the CMake command actually requires some arguments to be passed. Until then, please try this cmake command:

```cmake -DCMAKE_INSTALL_PREFIX=/path/to/install -DSOLVER_INCLUDE_HEADER_DIR=../examples/solvers -DMODEL_INCLUDE_HEADER_DIR=../examples/models -DSOLVER_INCLUDE_HEADER_NAME=solverinclude.h -DMODEL_INCLUDE_HEADER_NAME=modelinclude.h ..```

This will make sure you have all the solvers and models available, and then you won't have the error "SolverSP was not declared".

**Comment by mil-z** [comment]
Hi,

I installed SymPhas. I am also seeing some errors when I try to compile simple-driver with:
g++ main.cpp --std=c++17 -I/path/to/symphas-install/include -L/path/to/symphas-install/lib -lsymphas_all -ltbb
I get following errors:
modelmacros.h:358:27: error: ‘allowed_model_dimensions’ is not a class template
  358 | struct symphas::internal::allowed_model_dimensions<model_ ## NAME ## _t, D> \
         |                           ^~~~~~~~~~~~~~~~~~~~~~~~
modelmacros.h:359:1: error: qualified name does not name a class before ‘{’ token
  359 | { static const bool value = model_ ## NAME::allowed_model_dimensions<void, D>::value; };
         | ^
main.cpp:41:16: error: ‘SolverSP’ was not declared in this scope; did you mean ‘Solver’?
   41 |  model_EX_t<2, SolverSP<Stencil2d2h<5, 9, 6>>> model{ pp };
        |                ^~~~~~~~
        |                Solver
main.cpp:41:44: error: template argument 2 is invalid
   41 |  model_EX_t<2, SolverSP<Stencil2d2h<5, 9, 6>>> model{ pp };
        |                                            ^~
main.cpp:41:46: error: expected unqualified-id before ‘>’ token
   41 |  model_EX_t<2, SolverSP<Stencil2d2h<5, 9, 6>>> model{ pp };
        |                                              ^
main.cpp:42:25: error: ‘model’ was not declared in this scope; did you mean ‘Model’?
   42 |  symphas::find_solution(model, dt, 50);
      |                         ^~~~~
      |                         Model
main.cpp:43:30: error: expected primary-expression before ‘)’ token
   43 |  auto pfdata = model.grid<0>();
        |                              ^

my g++ version is:
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

Thank you.

**Comment by MetricManifold** [comment]
From the most recent updates, this issue has now been addressed.

**Comment by MetricManifold** [comment]
From the most recent updates, this issue has now been addressed.
